#creates pairs of versions using zip_keys, lists must be the same length
python:
  - 3.10
  - 3.10
  - 3.10
  - 3.10
  - 3.11
  - 3.11
  - 3.11
  - 3.11
  - 3.12
numpy:
  - 1.23
  - 1.24
  - 1.25
  - 1.26
  - 1.23
  - 1.24
  - 1.25
  - 1.26
  - 1.26
zip_keys:
  - python
  - numpy
