package:
  name: ccpi-regulariser
  version: {{CIL_VERSION}}

build:
  skip: True # [py==38 and np==115]
  preserve_egg_dir: False
  number: 0
  script_env:
    - CIL_VERSION

test:
  source_files:
    - ./test/
  commands:
    - python -c "import os; print (os.getcwd())"
    - python -m unittest discover -s test
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cython
    - vc 14 # [win]
    - cmake
    - ripgrep

  run:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python
    - vc 14 # [win]
    - libgcc-ng # [unix]

about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
