# https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files
# TODO: use scikit-build-core & setuptools_scm instead
{% set project = load_file_data('../src/Python/pyproject.toml', from_recipe_dir=True).get('project', {}) %}
package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

build:
  preserve_egg_dir: False
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

source:
  path: ..

test:
  source_files:
    - ./test/
  commands:
    - python -c "import os; print (os.getcwd())"
    - pytest -s
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - pip
    - vc 14 # [win]
    - cmake
    - pytest
    - imageio

  run:
    - {{ pin_compatible('numpy', min_pin='x.x', max_pin='x.x') }}
    - python
    - pytest
    - imageio
    - vc 14 # [win]
    - libgcc-ng # [unix]

about:
  home: https://tomographicimaging.github.io/CIL/
  license:  Apache-2.0
  summary: 'The set of CPU/GPU optimised regularisation modules for iterative image reconstruction and other image processing tasks'
