package:
  name: ccpi-regulariser
  version: {{CIL_VERSION}}

build:
  preserve_egg_dir: False
  number: 0
  script_env:
    - CIL_VERSION

test:
  source_files:
    - ./test/
#  requires:
#    - pillow
#    - pillow=4.1.1 # [win]
  commands:
    - python -c "import os; print (os.getcwd())"
    - python -m unittest discover -s test
requirements:
  build:
    - python
    - numpy {{ numpy }}
    - setuptools
    - cython
    - vc 14 # [win and py36]
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - cmake
    - ripgrep

  run:
    - {{ pin_compatible('numpy', max_pin='x.x') }}
    - python
    - numpy
    - vc 14 # [win and py36]
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]
    - libgcc-ng # [unix]

about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
