# https://docs.conda.io/projects/conda-build/en/stable/resources/define-metadata.html#loading-data-from-other-files
# TODO: use scikit-build-core & setuptools_scm instead
{% set project = load_file_data('../src/Python/pyproject.toml', from_recipe_dir=True).get('project', {}) %}
package:
  name: {{ project.get('name') }}
  version: {{ project.get('version') }}

build:
  preserve_egg_dir: False
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}
  ignore_run_exports_from:
    {% if cuda_compiler_version != '0' %}
    - {{ compiler('cuda') }}
    {% endif %}
  script_env:
    {% if cuda_compiler_version != '0' %}
    - BUILD_CUDA=ON
    {% else %}
    - BUILD_CUDA=OFF
    {% endif %}

source:
  path: ..

test:
  source_files:
    - ./test/
  commands:
    - python -m unittest discover -v -s test
requirements:
  build:
    - cmake
    - ninja
    - {{ compiler('cxx') }}
    {% if cuda_compiler_version != '0' %}
    - {{ compiler('cuda') }}
    {% endif %}

  host:
    - python x.x
    - setuptools
    - pip
    {% if cuda_compiler_version != '0' %}
    - cuda-version {{ cuda_compiler_version }}
    {% endif %}

  run:
    - numpy
    {% if cuda_compiler_version != '0' %}
    - {{ pin_compatible('cuda-version', min_pin='x', max_pin='x') }}
    {% endif %}

about:
  home: https://TomographicImaging.github.io/CIL
  license:  Apache-2.0
  summary: 'The set of CPU/GPU optimised regularisation modules for iterative image reconstruction and other image processing tasks'
