# pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
version = "24.0.0"
name='ccpi-regularisers'

[tool.setuptools.packages.find]
include = ["ccpi", "ccpi.*"]