package:
  name: ccpi-regulariser
  version: 0.10.3


build:
  preserve_egg_dir: False
  number: 0
  
test:
  files:
    - lena_gray_512.tif
  requires:
    - pillow

requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - cython
    - vc 14 # [win and py36] 
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]
    - cmake 

  run:
    - python
    - numpy x.x
    - vc 14 # [win and py36] 
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]
	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
