package:
  name: ccpi-regularizer
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy x.x
    - setuptools
    - boost ==1.64.0
    - boost-cpp ==1.64.0
    - cython
    - cil_regularizer
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]
    - cmake 

  run:
    - python
    - numpy x.x
    - boost ==1.64
    - cil_regularizer
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]

	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
