package:
  name: cil_regulariser
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env: 
    - CIL_VERSION

requirements:
  build:
    - cmake >=3.1
    - vc 14 # [win and py36] 
    - vc 14 # [win and py35] 
    - vc 9  # [win and py27]

  run:
    - vc 14 # [win and py36]
    - vc 14 # [win and py35]
    - vc 9  # [win and py27]


about:
  home: http://www.ccpi.ac.uk
  license: Apache v2.0
  summary: Regulariser package from CCPi
