package:
  name: ccpi-regularizers
  version: {{ environ['CIL_VERSION'] }}


build:
  preserve_egg_dir: False
  script_env:
    - CIL_VERSION   
#  number: 0
  
requirements:
  build:
    - python
    - numpy
    - setuptools
    - boost ==1.65
    - boost-cpp ==1.65
    - cython

  run:
    - python
    - numpy
    - boost ==1.64

	
about:
  home: http://www.ccpi.ac.uk
  license:  BSD license
  summary: 'CCPi Core Imaging Library Quantification Toolbox'
