name: build
on:
  release: {types: [published]}
  push:
    branches: [master]
    tags: ['**']
  pull_request:
    branches: [master]
jobs:
  conda-build:
    defaults: {run: {shell: 'bash -el {0}'}}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        python-version: [3.12, 3.13] # parallelise conda_build_config.yaml
        os: [ubuntu-latest, windows-2022, windows-2025]
      fail-fast: false
    steps:
    - uses: actions/checkout@v6
      with: {fetch-depth: 0, submodules: recursive}
    - if: startsWith(matrix.os, 'windows')
      uses: ilammy/msvc-dev-cmd@v1
    - uses: conda-incubator/setup-miniconda@v4
      with:
        python-version: ${{ matrix.python-version }}
        mamba-version: "*"
        channels: conda-forge
        conda-remove-defaults: "true"
    - name: conda build
      run: |
        if test ${{ matrix.python-version }} = 3.13; then
          BUILD_DEP=conda-build
          BUILD_CMD="conda build"
        else
          BUILD_DEP=boa
          BUILD_CMD="conda mambabuild"
        fi
        conda install $BUILD_DEP conda-verify
        $BUILD_CMD -c conda-forge --override-channels --output-folder dist recipe --python=${{ matrix.python-version }} --no-test
        $BUILD_CMD -c conda-forge --override-channels --test dist/*/ccpi-regulariser-*-cpu_*
    - uses: actions/upload-artifact@v7
      with:
        name: ccpi-regulariser-py${{ matrix.python-version}}-${{ matrix.os }}
        path: dist/*/ccpi-regulariser-*
